# cat ~/.actrc
# -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
# -P ubuntu-22.04=ghcr.io/catthehacker/ubuntu:act-22.04
# -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
# -P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
#


name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install --silent
    - run: npm run test
  demo:
    runs-on: ubuntu-22.04
    steps:
    - run: echo "I'am running inside a docker container"